name: Publish Package

on:
  release:
    types:
      - published

# Add permissions block at the top level of the workflow
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check if version is stable
        id: check_version
        run: |
          if [[ ! "${{ env.VERSION }}" =~ - ]]; then
            echo "STABLE=true" >> $GITHUB_ENV
          else
            echo "STABLE=false" >> $GITHUB_ENV
          fi

      # Publish to npm.
      - name: Publish to npm
        run: |
          if [[ "${{ env.STABLE }}" == "true" ]]; then
            npm publish
          else
            npm publish --tag next
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
